language: cpp
compiler: gcc

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Codecov
  - sudo pip install codecov
  # OCLint
  - wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/install_oclint
  - chmod +x install_oclint 
  - ./install_oclint

install: 
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  # cppcheck
  - sudo apt-get install -qq cppcheck

script: 
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # OCLint
  - wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/is_perfect/do_oclint
  - chmod +x do_oclint
  - ./do_oclint
  # Build, run and test the release version
  - wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/is_perfect/main.pro
  - wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/is_perfect/test
  - chmod +x test
  - ./test
  # Get code coverage badge (unneeded, codecov is tested by 'test' already
  - wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/is_perfect/get_code_cov
  - chmod +x get_code_cov
  - ./get_code_cov
  - codecov

